[misc]
welcome = " Rusty Password Manager"
confirm_input = "[Y]es | [N]o"

[input]
up_arrow = "[⏶] up"
down_arrow = "[⏷] down"
left_arrow = "[⏴] left"
right_arrow = "[⏵] right"
enter = "[↵] select"
escape = "[ESC] cancel"


[main_menu]
heading = "Main Menu"
add_account = "[1] Add new Account"
list_accounts = "[2] List all Accounts"
set_master_pwd = "[3] Set new master password"
wipe_database = "[4] Wipe Database"
exit = "[5] Exit"

[account]
account_name = "Name:"
email = "Email:"
password = "Password:"

[add_account]
heading = "Add new Account"
account_exists = "There is already an account called"
add_email_question = "Add email for this account?"
generate_pwd_question = "Generate password for account?"
pwd_generated = "Secure password has been generated."
pwd_set = "Password set"
cancel_question = "Do you want to cancel the account creation?"

[list_accounts]
heading = "Accounts"
search = "Search:"
search_input = "[S]earch"
quit_input = "[Q]uit"

[show_account]
heading = "Account"
delete_question = "Do you want to delete this account?"
save_question = "Save changes?"
copy_msg = "Copied password to clipboard"
copy_countdown = "Clearing clipboard in "
copy_input = "[C]opy password to clipboard"
edit_input = "[E]dit"
delete_input = "[D]elete"
quit_input = "[Q]uit"

[auth]
enter_pwd_promt = "Please enter master password"
invalid_pwd = "Invalid password!"
valid_pwd = "Password correct!"
set_new_master_pwd = "Set new master password:"
confirm_new_master_pwd = "Confirm new master password:"
master_password_set = "Master password set!"
confirm_failed = "Confirmation failed!"
cancel_question = "Do you want to cancel setting a new master password?"

[wipe]
are_you_sure_question = "Are you sure your want to wipe the database?"
warning = "This action cannot be undone!"
delete_msg = "Deleting database... Confirmation required."
enter_pwd_request = "Enter master password to confirm:"
success_msg = "Database wiped successfully!"
failure_msg = "Master Password wrong! Failed to wipe the database!"